[package]
name = "oxidizer-linux"
version = "0.1.0"
authors = ["Ethan Hunter <fc.spaceman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
